services:
  # MongoDB for the auth service
  mongo_db:
    image: mongo:8.0
    container_name: mongodb-db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./db-data/mongo-data:/data/db

  # Authentication Service (using MongoDB)
  auth-micro-service:
    build: ./
    container_name: auth-service
    image: dhruv4023/auth-server:latest
    ports:
      - "${AUTH_APP_PORT}:${AUTH_APP_PORT}"
    depends_on:
      mongo_db:
        condition: service_started
    environment:
      APP_PORT: ${AUTH_APP_PORT}
      DB_URL: ${MONGO_DB_URL} 
      DB_NAME: ${MONGO_DB_NAME} 
      SENDER_EMAIL: ${SENDER_EMAIL}
      SENDER_PASSWORD: ${SENDER_PASSWORD}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
